name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: gen timestamp
      id: version
      run: date +%y%m%d-%H%m
    - name: Run a multi-line script
      env:
        version: ${{steps.version.outputs}} 
      shell: bash
      run: |
        echo Add other actions to build,
        echo $version
        ver=`date +%y%m%d-%H%m`
        echo $ver
        
    
